# zookeeper-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: sta-salud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: apachepulsar/pulsar:latest
        env:
        - name: metadataStoreUrl
          value: "zk:zookeeper:2181"
        command: ["/bin/bash", "-c"]
        args:
          - >
            bin/apply-config-from-env.py conf/zookeeper.conf &&
            bin/generate-zookeeper-config.sh conf/zookeeper.conf &&
            exec bin/pulsar zookeeper
        #volumeMounts:
        #- name: zookeeper-data
        #  mountPath: /pulsar/data/zookeeper
        livenessProbe:
          exec:
            command: ["bin/pulsar-zookeeper-ruok.sh"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      #volumes:
      #- name: zookeeper-data
      #  persistentVolumeClaim:
      #    claimName: zookeeper-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: sta-salud
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: zookeeper-data-pvc
#  namespace: sta-salud
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
---
# pulsar-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pulsar-init
  namespace: sta-salud
spec:
  template:
    spec:
      containers:
      - name: pulsar-init
        image: apachepulsar/pulsar:latest
        command: ["/bin/bash", "-c"]
        args:
        - >
          bin/pulsar initialize-cluster-metadata
          --cluster cluster-a
          --zookeeper zookeeper:2181
          --configuration-store zookeeper:2181
          --web-service-url http://broker:8080
          --broker-service-url pulsar://broker:6650
      restartPolicy: OnFailure

---
# Bookie Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookie
  namespace: sta-salud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookie
  template:
    metadata:
      labels:
        app: bookie
    spec:
      containers:
      - name: bookie
        image: apachepulsar/pulsar:latest
        env:
        - name: clusterName
          value: "cluster-a"
        - name: zkServers
          value: "zookeeper:2181"
        - name: metadataServiceUri
          value: "metadata-store:zk:zookeeper:2181"
        - name: advertisedAddress
          value: "bookie"
        - name: BOOKIE_MEM
          value: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m"
        command:
        - bash
        - -c
        - "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
        #volumeMounts:
        #- name: bookkeeper-data
        #  mountPath: /pulsar/data/bookkeeper
      #volumes:
      #- name: bookkeeper-data
      #  persistentVolumeClaim:
      #    claimName: bookkeeper-pvc

---
# Bookkeeper PVC
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: bookkeeper-pvc
#  namespace: sta-salud
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
---
# Broker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: sta-salud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      hostname: broker
      containers:
      - name: broker
        image: apachepulsar/pulsar:latest
        ports:
        - containerPort: 6650
        - containerPort: 8080
        env:
        - name: metadataStoreUrl
          value: "zk:zookeeper:2181"
        - name: zookeeperServers
          value: "zookeeper:2181"
        - name: clusterName
          value: "cluster-a"
        - name: managedLedgerDefaultEnsembleSize
          value: "1"
        - name: managedLedgerDefaultWriteQuorum
          value: "1"
        - name: managedLedgerDefaultAckQuorum
          value: "1"
        - name: advertisedAddress
          value: "broker"
        - name: advertisedListeners
          value: "local:pulsar://broker:6650,external:pulsar://127.0.0.1:6650"
        - name: PULSAR_MEM
          value: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m"
        - name: isAllowAutoUpdateSchema
          value: "true"
        command:
        - bash
        - -c
        - "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
        readinessProbe:
          exec:
            command:
            - bin/pulsar-admin
            - brokers
            - list
            - cluster-a
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
---
# Broker Service
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: sta-salud
spec:
  selector:
    app: broker
  ports:
    - port: 6650
      targetPort: 6650
      name: pulsar
    - port: 8080
      name: http
      targetPort: 8080