apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# INGESTION DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-db
  #namespace: sta-salud
  labels:
    app: ingestion-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-db
  template:
    metadata:
      labels:
        app: ingestion-db
    spec:
      containers:
      - name: ingestion-db
        image: postgres:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "256Mi"
            cpu: "300m"
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_NAME
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -d
            - $(POSTGRES_DB)
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: ingestion-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: ingestion-data
        persistentVolumeClaim:
          claimName: ingestion-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-db
spec:
  selector:
    app: ingestion-db
  ports:
  - port: 5432
    targetPort: 5432     
---
# INGESTION APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: us-central1-docker.pkg.dev/saludtech-alpes/sta-images/ingestion:latest
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "256Mi"
            cpu: "300m"
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_NAME
        - name: PULSAR_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: PULSAR_BROKER_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: REDIS_PORT
---
# INGESTION CONSUMER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-consumer
  #namespace: sta-salud
  labels:
    app: ingestion-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-consumer
  template:
    metadata:
      labels:
        app: ingestion-consumer
    spec:
      containers:
      - name: ingestion-consumer
        image: us-central1-docker.pkg.dev/saludtech-alpes/sta-images/ingestion:latest
        command: ["python", "-u", "start_consumers.py"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "256Mi"
            cpu: "300m"
            ephemeral-storage: "2Gi"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_NAME
        - name: PULSAR_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: PULSAR_BROKER_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: REDIS_PORT
---
# INGESTION WORKER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-worker
  #namespace: sta-salud
  labels:
    app: ingestion-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-worker
  template:
    metadata:
      labels:
        app: ingestion-worker
    spec:
      containers:
      - name: ingestion-worker
        image: us-central1-docker.pkg.dev/saludtech-alpes/sta-images/ingestion:latest
        command: ["celery", "-A", "celery_worker", "worker", "--loglevel=info"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "256Mi"
            cpu: "300m"
            ephemeral-storage: "2Gi"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: ingestion-db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: INGESTION_DB_NAME
        - name: PULSAR_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: PULSAR_BROKER_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: REDIS_PORT
---      
# HEALTHCHECK
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingestion-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8000
    type: HTTP
    requestPath: /ingestion/health
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  annotations:
    cloud.google.com/backend-config: '{"default": "ingestion-config"}'  
spec:
  selector:
    app: ingestion
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 31025
