apiVersion: v1
kind: Service
metadata:
  name: servicio-auditoria
  namespace: sta-salud
  annotations:
    cloud.google.com/backend-config: '{"default": "auditoria-config"}'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8002
      protocol: TCP
      nodePort: 31021
  selector:
    app: auditoria
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditoria
  namespace: sta-salud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditoria
  template:
    metadata:
      labels:
        app: auditoria
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: POSTGRES_DB
          value: "postgres_auditoria_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditoria
  namespace: sta-salud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditoria
  template:
    metadata:
      labels:
        app: auditoria
    spec:
      containers:
      - name: auditoria
        image: us-central1-docker.pkg.dev/saludtech-alpes/sta-images/auditoria:latest
        command: ["flask", "--app", "api", "run", "--host", "0.0.0.0", "--port", "8002", "--debugger"]
        ports:
        - containerPort: 8002
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: DB_HOST
          value: "auditoria-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres_auditoria_db"
        - name: PULSAR_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: pulsar-config
              key: BROKER_HOST
---      
# HEALTHCHECK
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: auditoria-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8000
    type: HTTP
    requestPath: /auditoria/health