apiVersion: v1
kind: Service
metadata:
  name: servicio-ingestion
  namespace: sta-salud
  annotations:
    cloud.google.com/backend-config: '{"default": "ingestion-config"}'  
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 31020
  selector:
    app: ingestion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-db
  namespace: sta-salud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-db
  template:
    metadata:
      labels:
        app: ingestion-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: POSTGRES_DB
          value: "postgres_ingestion_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: sta-salud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: us-central1-docker.pkg.dev/saludtech-alpes/sta-images/ingestion:latest
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: DB_HOST
          value: "ingestion-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres_ingestion_db"
        - name: PULSAR_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: pulsar-config
              key: BROKER_HOST
---      
# HEALTHCHECK
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingestion-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8000
    type: HTTP
    requestPath: /ingestion/ping