apiVersion: v1
kind: Service
metadata:
  name: auditoria-service
  namespace: sta-salud
  annotations:
    cloud.google.com/backend-config: '{"default": "auditoria-config"}'
spec:
  selector:
    app: auditoria
  type: NodePort
  ports:
    - port: 80
      targetPort: 8002
      protocol: TCP
      nodePort: 31021

---
# AUDITORIA DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auditoria-db
  namespace: sta-salud
  labels:
    app: auditoria-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  auditoria-db
  template:
    metadata:
      labels:
        app:  auditoria-db
    spec:
      containers:
      - name: auditoria-db
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: auditoria-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: auditoria-db-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: AUDITORIA_DB_NAME

---
# AUDITORIA APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditoria
  namespace: sta-salud
  labels:
    app: auditoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditoria
  template:
    metadata:
      labels:
        app: auditoria
    spec:
      containers:
      - name: auditoria
        image: us-central1-docker.pkg.dev/saludtech-alpes/sta-images/auditoria:latest
        command: ["flask", "--app", "api", "run", "--host", "0.0.0.0", "--port", "8002", "--debugger"]
        ports:
        - containerPort: 8002
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: auditoria-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sta-db-secrets
              key: auditoria-db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: AUDITORIA_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: AUDITORIA_DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: AUDITORIA_DB_NAME
        - name: PULSAR_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: sta-config
              key: PULSAR_BROKER_URL
---      
# HEALTHCHECK
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: auditoria-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8002
    type: HTTP
    requestPath: /auditoria/health