###################################
# INGRESS
###################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: sta-salud
  labels:
    name: gateway-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "sta-ingress-ip"
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /ingestion
            backend:
              service:
                name: servicio-ingestion
                port:
                  number: 80
          - pathType: Prefix
            path: /anonimizacion
            backend:
              service:
                name: servicio-anonimizacion
                port:
                  number: 80